name: Lab 3 Multi-stage Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Stage 1: Test
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pytest

      - name: Run Unit Tests
        run: python -m pytest tests/

  # Stage 2: Build
  build:
    needs: test # Етап збірки почнеться ТІЛЬКИ після успішних тестів
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Artifact
        # Створюємо текстовий файл, що імітує результат збірки (артифакт)
        run: |
          echo "Application Build: bookstore-v1.0.${{ github.run_number }}" > build_result.txt
          echo "Status: Success" >> build_result.txt

      - name: Upload Artifact
        # Зберігаємо артифакт у GitHub, щоб передати його на деплой
        uses: actions/upload-artifact@v4
        with:
          name: bookstore-package
          path: build_result.txt

  # Stage 3: Deploy to Staging
  deploy_staging:
    needs: build # Залежить від успішної збірки артифакта
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        # Завантажуємо створений раніше артифакт
        uses: actions/download-artifact@v4
        with:
          name: bookstore-package

      - name: Simulate Staging Deploy
        # Імітуємо деплой, виводячи вміст артифакта
        run: |
          echo "Deploying to Staging environment..."
          cat build_result.txt
  # Stage 4: Verify Staging
  verify_staging:
    needs: deploy_staging # Запускається тільки після деплою
    runs-on: ubuntu-latest
    steps:
      - name: Run Smoke Tests
        # Імітуємо запуск смоук-тестів через Assert
        run: |
          echo "Verifying Staging environment..."
          python -c "assert 1 == 1"
          echo "Verification successful!"

  # Stage 5: Deploy to Production
  deploy_production:
    needs: verify_staging # Запускається тільки після успішної перевірки стейджингу
    runs-on: ubuntu-latest
    environment: production # Вказуємо середовище для ручного підтвердження
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: bookstore-package

      - name: Final Deploy to Production
        run: |
          echo "Deploying to Production environment..."
          cat build_result.txt
          echo "Deployment successful!"